Feat/remote zarr
sdsc-ordes/modo-api pull request #20
Opened 2024-03-06 14:05 UTC by almutlue

Related to https://github.com/sdsc-ordes/modo-api/issues/15:
__Main goal:__
Add capabilities to locally instantiate remote modo(s).

__Includes__:
- `modo.api.MODO()` accepts and handles remote s3 paths
- modo.remote includes new functions `list_remote_items()`, `get_metadata_from_remote()`  and `get_s3_path()` to directly access modo.server endpoints
- new modo.server endpoint to get the public s3 path of all modos match a query

__Open question__:
1. I'm happy to add matching cli functions e.g. `modo list REMOTE_URL` etc.. Would that be useful?
2. `modo.helpers.split_s3_url()` works with simple and unstable string manipulation. I would prefer something more robust! If we want to keep the current setup with one remote path we need to somehow split it into `s3 endpoint url` and `bucket path + modo_path`to align with the syntax of `zarr.open_gorup()`. I couldn't find a good alternative to this. We could do something like: 
```py
class MODO:
    def __init__(
        self,
        path: Union[Path, str],
        s3_endpoint: Optional[str]
    ):
        if s3_endpoint:
            archive=...
``` 
This would require the user to specify the s3_endpoint in addition, though.
Any preferences or ideas to better solve this issue?

2024-03-06 17:44 UTC, cmdoret reviewed
This adds very useful functionality and the code is surprisingly simple! :100:

 I agree that the current implementation of `split_s3_url` is brittle and like your suggestion of having a separate `s3_endpoint` argument. This feels like a safer solution!

2024-03-06 17:44 UTC, cmdoret commented on deploy/modo-server/server.py
> +import rdflib
```suggestion
```
**question:** do we need this import?

2024-03-06 17:44 UTC, cmdoret commented on deploy/modo-server/server.py
> +        ]
**suggestion:** just found out about [`difflib.SequenceMatcher()`](https://docs.python.org/3/library/difflib.html#sequencematcher-objects), which is in python's standard library:

```python
>>> import difflib
>>> difflib.SequenceMatcher(None, 'example', 'example').ratio()
1.0
>>> difflib.SequenceMatcher(None, 'example', 'exemple').ratio()
0.8571428571428571
>>> difflib.SequenceMatcher(None, 'example', 'many examples').ratio()
0.7
>>> difflib.SequenceMatcher(None, 'lion', 'zebra').ratio()
0.0
```
We could maybe just apply a threshold on it?
There's also a `.real_quick_ratio()` which uses a heuristic to go much faster. We could also use this one?

2024-03-06 17:44 UTC, cmdoret commented on deploy/modo-server/server.py
> +        ]
```python
>>> %timeit difflib.SequenceMatcher(None, 'the lazy dog jumps over the lazy dog', 'the quick brown fox jumps over the lazy dog').ratio()
82.7 µs ± 5.29 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)

>>> %timeit difflib.SequenceMatcher(None, 'the lazy dog jumps over the lazy dog', 'the quick brown fox jumps over the lazy dog').real_quick_ratio()
9.83 µs ± 603 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
```

2024-03-06 17:44 UTC, cmdoret commented on modo/api.py
> +            self.path = Path(path)
**praise:** neat! I didn't realize you could do it so easily with zarr :)
**question:** this is simpler than what we use in modo_server (below). Would it make sense to  use the same pattern in there? Could we even remove the `archive` of `MODO` altogether?

https://github.com/sdsc-ordes/modo-api/blob/46ce93862bd6caab73d1ec65c89fab8735c1b7f6/deploy/modo-server/server.py#L42-L46

2024-03-06 17:44 UTC, cmdoret commented on modo/helpers.py
> +def split_s3_url(s3_url: str) -> tuple[str, str]:
**note:** this does indeed feel dangerous indeed if we keep that, I'd start by checking if the format matches our assumption (if possible) and raise an error if it doesn't.

2024-03-06 17:44 UTC, cmdoret commented on modo/remote.py
> +    remote_url: HttpUrl, id: Optional[str] = None
**praise:** simple yet very useful :D
**suggestion:** avoid shadowing built-in `id` (`id_`, `modo_id`, ...)

2024-03-06 17:44 UTC, cmdoret commented on modo/remote.py
> +) -> List:
```suggestion
) -> list[str]:
```
**note:** we require python >= 3.10, so lowercase type hints are legal :)

2024-03-08 10:14 UTC, cmdoret requested changes
Just had one suggestion for for a safer path processing when removing the bucket, otherwise everything looks great!

the changes are very minor and I'll apply them directly, hope that's ok

2024-03-08 10:54 UTC, cmdoret commented
I took the liberty to apply my suggestions for safer bucket replacement and added a bit of code to sort the output by similarity,

Since there was nothing else for me, I'll approve the PR and let you review the change I made.

2024-03-08 10:55 UTC, cmdoret approved these changes

2024-03-11 08:04 UTC, almutlue commented
Thanks a lot! Looks really good to me. I didn't know `removeprefix()` :-)

2024-03-11 08:05 UTC, merged